"""Initial migration - create all tables

Revision ID: 1e84e4b77ee4
Revises: b58fd50c2ec2
Create Date: 2025-12-28 04:04:07.244455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e84e4b77ee4'
down_revision: Union[str, Sequence[str], None] = 'b58fd50c2ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh_key', sa.String(), nullable=False),
    sa.Column('auth_key', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('content_fingerprint', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('is_duplicate', sa.Boolean(), nullable=False))
    op.add_column('jobs', sa.Column('original_job_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_jobs_content_fingerprint'), 'jobs', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_jobs_is_duplicate'), 'jobs', ['is_duplicate'], unique=False)
    op.create_foreign_key(None, 'jobs', 'jobs', ['original_job_id'], ['id'])
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('job_category', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('job_url', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('is_clicked', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('sent_via_email', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('sent_via_telegram', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('sent_via_push', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_job_id'), table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('alert_speed', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'in_app_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_pro',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'in_app_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'alert_speed')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index(op.f('ix_notifications_job_id'), 'notifications', ['job_id'], unique=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notifications', 'clicked_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'sent_via_push')
    op.drop_column('notifications', 'sent_via_telegram')
    op.drop_column('notifications', 'sent_via_email')
    op.drop_column('notifications', 'is_clicked')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'job_url')
    op.drop_column('notifications', 'job_category')
    op.drop_column('notifications', 'job_title')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_is_duplicate'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_fingerprint'), table_name='jobs')
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'original_job_id')
    op.drop_column('jobs', 'is_duplicate')
    op.drop_column('jobs', 'content_fingerprint')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
