"""add_google_email_column

Revision ID: 388cb1dfb9f0
Revises: dd01bf82913f
Create Date: 2026-01-05 16:50:34.935506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '388cb1dfb9f0'
down_revision: Union[str, Sequence[str], None] = 'dd01bf82913f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.add_column('users', sa.Column('google_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_email')
    op.create_table('system_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_scraping', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_scrape_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_jobs_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('twitter_cookies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_status_pkey'))
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    # ### end Alembic commands ###
