"""add_google_id_column

Revision ID: dd01bf82913f
Revises: 1e84e4b77ee4
Create Date: 2026-01-05 16:12:33.798715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd01bf82913f'
down_revision: Union[str, Sequence[str], None] = '1e84e4b77ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    # op.drop_table('system_status')
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    # op.create_table('system_status',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('is_scraping', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('last_scrape_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('last_jobs_found', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('last_error', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('twitter_cookies', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('system_status_pkey'))
    # )
    # op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    # ### end Alembic commands ###
